{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b1e90788-8207-4ac8-b6fc-7258d52de641",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'get_data'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[6], line 5\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mos\u001b[39;00m\n\u001b[1;32m      3\u001b[0m sys\u001b[38;5;241m.\u001b[39mpath\u001b[38;5;241m.\u001b[39mappend(os\u001b[38;5;241m.\u001b[39mpath\u001b[38;5;241m.\u001b[39mabspath(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124msrc\u001b[39m\u001b[38;5;124m\"\u001b[39m))\n\u001b[0;32m----> 5\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mget_data\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m download_nfl_data, download_cfb_data\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'get_data'"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "import os\n",
    "sys.path.append(os.path.abspath(\"src\"))\n",
    "\n",
    "from get_data import download_nfl_data, download_cfb_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "95d64959-4fda-44fa-894f-8031051f49db",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "RAW_DIR = os.path.join(\"data\", \"raw\")\n",
    "PROC_DIR = os.path.join(\"data\", \"processed\")\n",
    "\n",
    "\n",
    "def _ensure_dir(path: str) -> None:\n",
    "    os.makedirs(path, exist_ok=True)\n",
    "\n",
    "def clean_nfl_team_stats(season: int = 2024) -> None:\n",
    "    \"\"\"\n",
    "    Clean NFL data obtained from API\n",
    "    Flattens data (json data to be loaded into CSV)\n",
    "    Isolates Chicago Bears data for comparison\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    season : int, optional\n",
    "        Data from which season should be obtained from API call.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    NoneType\n",
    "        saves raw data to external file\n",
    "    \"\"\"\n",
    "    json_path = os.path.join(RAW_DIR, \"nfl\", f\"team_season_stats_{season}.json\")\n",
    "    if not os.path.exists(json_path):\n",
    "        print(f\"[NFL] Missing raw file: {json_path}\")\n",
    "        return\n",
    "\n",
    "    with open(json_path, \"r\", encoding=\"utf-8\") as f:\n",
    "        data = json.load(f)\n",
    "\n",
    "    df = pd.json_normalize(data)\n",
    "\n",
    "    _ensure_dir(PROC_DIR)\n",
    "    league_path = os.path.join(PROC_DIR, f\"nfl_team_stats_{season}.csv\")\n",
    "    df.to_csv(league_path, index=False)\n",
    "    print(f\"[NFL] Saved league team stats to {league_path}\")\n",
    "\n",
    "    bears_mask = df[\"Team\"].isin([\"CHI\", \"Chicago Bears\"])\n",
    "    bears_df = df[bears_mask].copy()\n",
    "    bears_path = os.path.join(PROC_DIR, f\"bears_team_stats_{season}.csv\")\n",
    "    bears_df.to_csv(bears_path, index=False)\n",
    "    print(f\"[NFL] Saved Bears-only stats to {bears_path}\")\n",
    "\n",
    "\n",
    "def clean_cfb_player_stats(year=2024) -> None:\n",
    "    \"\"\"\n",
    "    Clean obtained college football player data\n",
    "    Flattens data (json data to be loaded into CSV)\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    year : int, optional\n",
    "        Data from which season data is from \n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    NoneType\n",
    "        saves raw data to external file\n",
    "    \"\"\"\n",
    "    \n",
    "    path = f\"data/raw/college/player_stats_{year}.json\"\n",
    "    df = pd.json_normalize(json.load(open(path)))\n",
    "\n",
    "    # Ensure statName and statValue exist\n",
    "    if {\"statType\", \"stat\", \"statValue\"}.intersection(df.columns):\n",
    "        # CFBD sometimes uses statType or statName\n",
    "        stat_col = \"statName\" if \"statName\" in df.columns else \"statType\"\n",
    "        value_col = \"statValue\" if \"statValue\" in df.columns else \"stat\"\n",
    "\n",
    "        id_cols = [\"playerId\", \"player\", \"position\", \"team\", \"conference\"]\n",
    "\n",
    "        wide = df.pivot_table(\n",
    "            index=id_cols,\n",
    "            columns=stat_col,\n",
    "            values=value_col,\n",
    "            aggfunc=\"sum\",\n",
    "        ).reset_index()\n",
    "\n",
    "        wide.to_csv(f\"data/processed/cfb_player_stats_{year}.csv\", index=False)\n",
    "        print(\"Saved clean wide-format CFB stats.\")\n",
    "\n",
    "\n",
    "def main() -> None:\n",
    "    clean_nfl_team_stats(season=2024)\n",
    "    clean_cfb_player_stats(year=2024)\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
