{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "7f110683-08d0-4ca4-b1ee-51ffaf78b8f9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Imports\n",
    "import os\n",
    "import json\n",
    "import requests\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "5b3ea02c-67a1-4c15-bd58-8fb81034be34",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[NFL] Requesting team season stats: https://api.sportsdata.io/v3/nfl/stats/json/TeamSeasonStats/2024\n",
      "[NFL] Saved team season stats to data/raw/nfl/team_season_stats_2024.json\n",
      "[CFB] Requesting player season stats: https://api.collegefootballdata.com/stats/player/season with {'year': 2024, 'seasonType': 'regular'}\n",
      "[CFB] Saved player stats JSON to data/raw/college/player_stats_2024.json\n"
     ]
    }
   ],
   "source": [
    "\n",
    "RAW_DIR = os.path.join(\"data\", \"raw\")\n",
    "\n",
    "# API Keys from Free APIs\n",
    "os.environ[\"NFL_API_KEY\"] = \"09847b815a194e83896f07413c69f2b7\"\n",
    "os.environ[\"CFB_API_KEY\"] = \"zft1B/YA/d2sjw+egpu0NMbxWBAVI1m+1p5HG4iCehjdXDw6HvNjXaBBKiZpFhIb\"\n",
    "\n",
    "\n",
    "def _ensure_dir(path: str) -> None:\n",
    "    os.makedirs(path, exist_ok=True)\n",
    "\n",
    "# making sure envs are assigned correctly\n",
    "def _check_env_var(name: str) -> str:\n",
    "    val = os.getenv(name)\n",
    "    if not val:\n",
    "        raise RuntimeError(\n",
    "            f\"Environment variable {name} is not set. \"\n",
    "            f\"Set it before running (e.g., export {name}=YOUR_KEY_HERE).\"\n",
    "        )\n",
    "    return val\n",
    "\n",
    "\n",
    "# Getting NFL season data from API\n",
    "def download_nfl_team_season_stats(season: int = 2024) -> None:\n",
    "    \"\"\"\n",
    "    Download NFL stats for comparison\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    season : int, optional\n",
    "        Data from which season should be obtained from API call.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    NoneType\n",
    "        saves raw data to external file\n",
    "    \"\"\"\n",
    "    nfl_key = _check_env_var(\"NFL_API_KEY\")\n",
    "    url = f\"https://api.sportsdata.io/v3/nfl/stats/json/TeamSeasonStats/{season}\"\n",
    "    print(f\"[NFL] Requesting team season stats: {url}\")\n",
    "\n",
    "    headers = {\"Ocp-Apim-Subscription-Key\": nfl_key}\n",
    "    resp = requests.get(url, headers=headers, timeout=30)\n",
    "    resp.raise_for_status()\n",
    "\n",
    "    data = resp.json()\n",
    "    save_path = os.path.join(RAW_DIR, \"nfl\", f\"team_season_stats_{season}.json\")\n",
    "    _ensure_dir(os.path.dirname(save_path))\n",
    "    with open(save_path, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump(data, f, indent=2)\n",
    "    print(f\"[NFL] Saved team season stats to {save_path}\")\n",
    "\n",
    "\n",
    "# College football players stats API\n",
    "def download_cfb_player_stats(year: int = 2024) -> None:\n",
    "    \"\"\"\n",
    "    Download college football player data\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    season : int, optional\n",
    "        Data from which season should be obtained from API call.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    NoneType\n",
    "        saves raw data to external file\n",
    "    \"\"\"\n",
    "    \n",
    "    cfb_key = _check_env_var(\"CFB_API_KEY\")\n",
    "    url = \"https://api.collegefootballdata.com/stats/player/season\"\n",
    "    params = {\n",
    "        \"year\": year,\n",
    "        \"seasonType\": \"regular\",\n",
    "    }\n",
    "    headers = {\"Authorization\": f\"Bearer {cfb_key}\"}\n",
    "\n",
    "    print(f\"[CFB] Requesting player season stats: {url} with {params}\")\n",
    "    resp = requests.get(url, headers=headers, params=params, timeout=60)\n",
    "    resp.raise_for_status()\n",
    "\n",
    "    data = resp.json()\n",
    "    save_path = os.path.join(RAW_DIR, \"college\", f\"player_stats_{year}.json\")\n",
    "    _ensure_dir(os.path.dirname(save_path))\n",
    "    with open(save_path, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump(data, f, indent=2)\n",
    "    print(f\"[CFB] Saved player stats JSON to {save_path}\")\n",
    "\n",
    "\n",
    "def main() -> None:\n",
    "    _ensure_dir(RAW_DIR)\n",
    "\n",
    "    # calling above functions\n",
    "\n",
    "    \n",
    "    download_nfl_team_season_stats(season=2024)\n",
    "\n",
    "    download_cfb_player_stats(year=2024)\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
